version: '3.9'

services:
  airbnb:
    build: .
    container_name: airbnb
    restart: on-failure
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - mongo_network

networks:
  mongo_network:
    name: mongo_default
    external: true
